// ui/src/lib/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
    size?: 'sm' | 'md' | 'lg';
    iconLeft?: Snippet;
    iconRight?: Snippet;
    fullWidth?: boolean;
    loading?: boolean;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    class?: string;
    onclick?: (e: MouseEvent) => void;
    children?: Snippet;
  }

  let {
    variant = 'primary',
    size = 'md',
    iconLeft,
    iconRight,
    fullWidth = false,
    loading = false,
    disabled = false,
    type = 'button',
    class: className = '',
    onclick,
    children,
  }: Props = $props();
</script>

<button
  class="om-btn om-btn--{variant} om-btn--{size} {fullWidth ? 'om-btn--block' : ''} {loading
    ? 'om-btn--loading'
    : ''} {className}"
  {type}
  disabled={disabled || loading}
  aria-disabled={disabled || loading || undefined}
  {onclick}
>
  {#if loading}
    <span class="om-btn__spin" aria-hidden="true"></span>
  {/if}
  {#if iconLeft}
    {@render iconLeft()}
  {/if}
  <span class="om-btn__label">{@render children?.()}</span>
  {#if iconRight}
    {@render iconRight()}
  {/if}
</button>

<style>
  :global(.om-btn) {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: var(--space-2);
    font-family: var(--font-sans);
    font-weight: var(--weight-medium);
    line-height: 1;
    border-radius: var(--radius-md);
    border: 1px solid transparent;
    cursor: pointer;
    transition:
      var(--transition-colors),
      box-shadow var(--duration-fast) var(--ease-standard);
    white-space: nowrap;
    user-select: none;
    text-decoration: none;
    position: relative;
  }
  :global(.om-btn:focus-visible) {
    outline: none;
    box-shadow: var(--shadow-focus);
  }
  :global(.om-btn[disabled], .om-btn[aria-disabled='true']) {
    opacity: 0.45;
    pointer-events: none;
  }
  :global(.om-btn svg) {
    width: 1.15em;
    height: 1.15em;
    flex: 0 0 auto;
  }
  :global(.om-btn--sm) {
    font-size: var(--text-sm);
    padding: 0 12px;
    height: 32px;
  }
  :global(.om-btn--md) {
    font-size: var(--text-base);
    padding: 0 16px;
    height: 40px;
  }
  :global(.om-btn--lg) {
    font-size: var(--text-md);
    padding: 0 22px;
    height: 48px;
  }
  :global(.om-btn--primary) {
    background: var(--accent);
    color: var(--text-on-accent);
  }
  :global(.om-btn--primary:hover) {
    background: var(--accent-hover);
  }
  :global(.om-btn--primary:active) {
    background: var(--accent-press);
  }
  :global(.om-btn--secondary) {
    background: var(--surface);
    color: var(--text-strong);
    border-color: var(--border-default);
  }
  :global(.om-btn--secondary:hover) {
    background: var(--bg-subtle);
    border-color: var(--border-strong);
  }
  :global(.om-btn--ghost) {
    background: transparent;
    color: var(--text-body);
  }
  :global(.om-btn--ghost:hover) {
    background: var(--bg-subtle);
  }
  :global(.om-btn--danger) {
    background: var(--danger);
    color: #fff;
  }
  :global(.om-btn--danger:hover) {
    background: var(--danger-hover);
  }
  :global(.om-btn--block) {
    width: 100%;
  }
  :global(.om-btn--loading .om-btn__label, .om-btn--loading svg) {
    visibility: hidden;
  }
  :global(.om-btn__spin) {
    position: absolute;
    width: 1.1em;
    height: 1.1em;
    border: 2px solid currentColor;
    border-right-color: transparent;
    border-radius: 50%;
    animation: om-spin 0.6s linear infinite;
  }
</style>

// design/Button.jsx
import React from "react";

const css = `
.om-avatar{display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto;
  border-radius:var(--radius-full);overflow:hidden;font-family:var(--font-display);
  font-weight:var(--weight-medium);color:var(--text-strong);background:var(--bg-sunken);
  border:1px solid var(--border-subtle);position:relative;user-select:none}
.om-avatar img{width:100%;height:100%;object-fit:cover;display:block}
.om-avatar--xs{width:24px;height:24px;font-size:10px}
.om-avatar--sm{width:30px;height:30px;font-size:12px}
.om-avatar--md{width:38px;height:38px;font-size:14px}
.om-avatar--lg{width:48px;height:48px;font-size:17px}
.om-avatar--agent{background:var(--stone-900);border-color:var(--signal-600);
  box-shadow:0 0 0 2px color-mix(in oklch,var(--signal-500) 35%,transparent)}
.om-avatar__status{position:absolute;right:-1px;bottom:-1px;width:30%;height:30%;
  min-width:8px;min-height:8px;border-radius:50%;border:2px solid var(--surface);background:var(--success)}
`;

if (typeof document !== "undefined" && !document.getElementById("om-avatar-css")) {
  const s = document.createElement("style");
  s.id = "om-avatar-css";
  s.textContent = css;
  document.head.appendChild(s);
}

function initials(name = "") {
  return name.trim().split(/\s+/).slice(0, 2).map((p) => p[0] || "").join("").toUpperCase();
}

export function Avatar({ name = "", src, size = "md", agent = false, status = false, className = "", ...rest }) {
  const cls = ["om-avatar", `om-avatar--${size}`, agent ? "om-avatar--agent" : "", className]
    .filter(Boolean).join(" ");
  return (
    <span className={cls} title={agent ? "omnara" : name} {...rest}>
      {agent ? (
        <img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 32 32' fill='none'><circle cx='16' cy='16' r='10.4' stroke='%23FAF8F3' stroke-width='3.2'/><circle cx='16' cy='16' r='2.6' fill='%23FAF8F3'/><circle cx='23.5' cy='8.5' r='3.6' fill='%232FC97A'/></svg>" alt="omnara" />
      ) : src ? (
        <img src={src} alt={name} />
      ) : (
        <span>{initials(name)}</span>
      )}
      {status && <span className="om-avatar__status" aria-hidden="true" />}
    </span>
  );
}
